services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: uenp_bet
      POSTGRES_USER: leandro
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leandro -d uenp_bet"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  api-lutadores:
    build: .
    container_name: api-lutadores
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Use o nome do serviço 'postgres-db', não 'db'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/uenp_bet
      SPRING_DATASOURCE_USERNAME: leandro
      SPRING_DATASOURCE_PASSWORD: 12345
